/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#dec1b0',
        'outline': '#a68b7d',
        'outline-variant': '#574236',
        'primary': '#ffb68a',
        'primary-container': '#f27a18',
        'on-primary': '#522300',
        'on-primary-fixed': '#321300',
        'on-primary-fixed-variant': '#743500',
        'secondary': '#ffdb9d',
        'secondary-container': '#feb700',
        'secondary-fixed-dim': '#ffba20',
        'tertiary': '#4de082',
        'tertiary-container': '#00b35c',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
      },
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'stats-xl': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'stats-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '700' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'gutter': '16px',
        'container-margin': '24px',
        'unit': '4px',
      },
    },
  },
  plugins: [],
};
