events { worker_connections 1024; }

http {
    server {
        listen 80;

        # Todo lo que vaya a la raíz irá al contenedor Frontend
        location / {
            proxy_pass http://frontend:8103;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Redirigir llamadas de Productos
        location /api/productos {
            proxy_pass http://productos-service:236/productos;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirigir llamadas de Inventario
        location /api/inventario {
            proxy_pass http://inventario-service:238/inventario;
            proxy_set_header Host $host;
        }

        # Redirigir llamadas de Pedidos
        location /api/pedidos {
            proxy_pass http://pedidos-service:237/pedidos;
            proxy_set_header Host $host;
        }
    }
}