events { worker_connections 1024; }

http {
    server {
        listen 80;

        # 1. Productos
        # Si React pide: /api/productos/productos
        # Nginx quita "/api/productos" y le pasa al backend solo "/productos"
        location /api/productos/ {
            proxy_pass http://productos-service:236/; # <--- OJO al "/" al final
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 2. Inventario
        # Si React pide: /api/inventario/inventario
        # Nginx lo convierte internamente en http://inventario-service:238/inventario
        location /api/inventario/ {
            proxy_pass http://inventario-service:238/; # <--- OJO al "/" al final
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Pedidos
        # Si React pide: /api/pedidos/pedidos
        location /api/pedidos/ {
            proxy_pass http://pedidos-service:237/; # <--- OJO al "/" al final
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 4. Autenticación
        # Si tu AuthContext pide: /api/auth/auth/login
        # Nginx quita "/api/auth/" y pasa al backend: http://auth-service:239/auth/login
        location /api/auth/ {
            proxy_pass http://auth-service:239/; # <--- OJO al "/" al final
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 5. Dozzle Logs
        location /logs/ {
            proxy_pass http://dozzle:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }

        # 6. Todo lo demás va al Frontend en el puerto de Vite (245)
        location / {
            proxy_pass http://frontend:245; 
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}